---
title: "Data_Recoding"
author: "Ayishat Yussuf"
date: "2025-09-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = here::here())
```
# Load Packages and Datasets

```{r}
library(readr) #read in csv files 
library(survey) #analysis for survey data (e.g NHANES)
library(magrittr) #pip operations (%>%) 
library(dplyr) #data manipulation (filter, select, mutate etc) 
library(ggplot2) #creating data visualizations/plots
```

```{r}

```


```{r}
#fsdhh
table(FullData_allcycles$FSDHH, useNA="ifany")
#305 missing

#Variables
FullData_allcycles<-FullData_allcycles%>%
  mutate(FOODSEC=case_when(
    FSDHH==1 ~1,  #fully food secure (ref)
    FSDHH==2 ~2, #marginally food secure (1-2)
    FSDHH==3 ~3, # low food security 
    FSDHH==4 ~4,  #very low food security 
    TRUE~NA_real_
  ))

table(FullData_allcycles$FOODSEC,useNA="ifany")
```

##Age
```{r}
summary(FullData_allcycles$RIDAGEYR, useNA="ifany")

class(FullData_allcycles$RIDAGEYR) #to see what type of variable you have 

FullData_allcycles<-FullData_allcycles%>%
  filter(FullData_allcycles$RIDAGEYR>=18) #filtered for observations Age greater than or equal to 18

quartiles<-quantile(FullData_allcycles$RIDAGEYR)
print(quartiles)

FullData_allcyclesFINAL$AGEGROUP<-cut(
  FullData_allcyclesFINAL$RIDAGEYR,
  breaks=quartiles, 
  include.lowest=TRUE, 
  labels= c("18-31", "32-46", "47-63", "64-85")
)

summary(FullData_allcyclesFINAL$AGEQ, useNA="ifany") 
#no missing
table(FullData_allcycles$AGEGROUP, useNA="ifany")
```
decided to keep male as reference - september 19th, 2025
```{r}
table(FullData_allcycles$RIAGENDR, useNA="ifany")

FullData_allcycles<-FullData_allcycles%>%
  mutate(SEX=ifelse(RIAGENDR==1, 1, 2))

levels(FullData_allcycles$SEX)<-(c("1", "2"))

table(FullData_allcycles$SEX, useNA="ifany")
```

```{r}
#Recode race/ethnicity 
table(FullData_allcycles$RIDRETH1, useNA="ifany")

FullData_allcycles<-FullData_allcycles%>%
  mutate(RACEETH=case_when(
    RIDRETH1==3 ~1,
    RIDRETH1==4 ~2, 
    RIDRETH1==1 ~3, 
    RIDRETH1==2 ~4, 
    RIDRETH1==5 ~5, 
    TRUE~NA_real_
  ))


table(FullData_allcycles$RACEETH, useNA="ifany")
```

```{r}
#education 
summary(FullData_allcycles$DMDEDUC3)
summary(FullData_allcycles$DMDEDUC3)
FullData_allcycles <- FullData_allcycles %>%
  mutate(EDUCAT = case_when(
   DMDEDUC3< 13 & RIDAGEYR<20 ~ 1,
    DMDEDUC2 < 3 ~ 1, 
    DMDEDUC2== 1 ~2, 
    DMDEDUC3 %in% c(13, 14, 15) ~ 2, 
    DMDEDUC2 == 3 ~ 2,
    DMDEDUC2 == 4 ~ 3,
    DMDEDUC2 == 5 ~ 4,
    TRUE ~ NA_real_
  ))

table(FullData_allcycles$EDUCAT, useNA="ifany")
```

```{r}
#poverty
summary(FullData_allcycles$INDFMPIR, useNA="ifany") #1513missing

FullData_allcycles<-FullData_allcycles%>%
  mutate(PIRCAT=case_when(
    INDFMPIR<=0.99 ~1, 
    INDFMPIR>=1 & INDFMPIR<2 ~2, 
    INDFMPIR>=2 & INDFMPIR<3 ~3, 
    INDFMPIR>=3 & INDFMPIR<5 ~4, 
    INDFMPIR>=5 ~5, 
    is.na(INDFMPIR)~NA_real_
  ))

table(FullData_allcycles$PIRCAT, useNA="ifany")
```

```{r}
#cycleyears
table(FullData_allcycles$cycleyr, useNA="ifany")

```
